openapi: '3.0.1'
info: 
  title: 'thing'
  version: '1.0.0'
  license:
    name: MIT
paths: 
  /thing:
    post:
      summary: create a thing
      operationId: postThing
      requestBody:
        description: thing that needs to be stored
        content: 
        required: true
      responses:
        200:
          description: ok
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
components:
  schemas:
    Thing:
      required:
        - id
        - unique
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
          example: information about the thing
        unique:
          type: boolean